---
title: "Weekly Summary Template"
author: "Author Name"
title-block-banner: true
title-block-style: default
toc: true
format: html
# format: pdf
---

---

## Tuesday, Jan 17

::: {.callout-important}
## TIL

Include a _very brief_ summary of what you learnt in this class here. 

Today, I learnt the following concepts in class:

1. The mosaic package is designed to facilitate the use of R in statistics and calculus instruction by providing a number of functions that make many common tasks fit into a common template
1. Matrixes are filled by column.
1. BY typing byrow = TRUE, you can have the matrix fill by row. 
:::

Provide more concrete details here. You can also use footenotes[^footnote] if you like

```{R results='hide'}
#| output: false
library(dplyr)
library(purrr)
```


For example: 
in class we learnt we learnt making matricies and how to format then to fill by row. 
```{R}
Brian <- matrix(
  c(1,2,3,4,5,6,7,8,9,1,2,3),
  nrow = 3,
  byrow = TRUE

)
```



## Thursday, Jan 19



::: {.callout-important}
## TIL

Include a _very brief_ summary of what you learnt in this class here. 

Today, I learnt the following concepts in class:

1. When dealing with tidy data, each row will be unique.
1. The library dplyr helps with data munipulation.
1. Joins allow you to comine two datasets
:::

Provide more concrete details here, e.g., 

In class we learnt how to use the `map` function to create multiple regression diagnostic plots

```{R}
```

I will take better notes in the future.
[^footnote]: You can include some footnotes here